### ISSUE TITLE
little data for Thailand TH

### ISSUE THREAD

**Issue by tyrcho** [sigpwned/popular-names-by-country-dataset#1]
Hey, thanks for sharing this dataset !

I wanted to reuse this to prepare a game of TTRPG which occurs in Thailand and wrote a [script](https://gitlab.com/tyrcho/code-samples/-/commit/e8fdf91be6a8771baecc932e8b34ecef066595ad) to  process the json version of the dataset to generate Markdown tables which can be used with https://github.com/javalent/dice-roller

Unfortunately after 2 hours of work I discovered that the dataset has ...
- 5 male surnames for TH
- no forenames at all

Any hope you can get more of these ? Or point me to where you found these names ?

**Comment by sigpwned** [comment]
Hello!

The short (perhaps unsatisfying) reason that I didn't include (m)any Thai surnames is that none appear in [the Wikipedia page I scraped the data from](https://en.wikipedia.org/wiki/Lists_of_most_common_surnames). (You might find [this link](https://en.wikipedia.org/wiki/Lists_of_most_common_surnames_in_Asian_countries#Thailand) useful to understand why that may be.)

The story is similar for [forenames](https://en.wikipedia.org/wiki/List_of_most_popular_given_names).

That said, Wikipedia taketh away, but Wikipedia also giveth!

You can find some common Thai surnames (such as they are, per the previous link) [here](https://en.wikipedia.org/wiki/Category:Thai-language_surnames) on Wikipedia (with some additional context [here](https://en.wikipedia.org/wiki/Category:Thai_families)), plus [masculine](https://en.wikipedia.org/wiki/Category:Thai_masculine_given_names) and [feminine](https://en.wikipedia.org/wiki/Category:Thai_feminine_given_names) forenames.

You might also find [this Reddit thread](https://www.reddit.com/r/namenerds/comments/ekaxzp/thai_names/) interesting.

I hope that helps! Please don't hesitate to respond here or open another issue if you have any more questions!
